"""
Theme Model

Aggregated topic from multiple related events.
"""
from datetime import datetime
from typing import Optional, List, TYPE_CHECKING

from sqlalchemy import String, Integer, Float, DateTime, Text, Index, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..base import Base, TimestampMixin

if TYPE_CHECKING:
    from .signal import Signal


class Theme(Base, TimestampMixin):
    """
    Aggregated topic from multiple related events.
    
    Themes emerge when multiple events share similar topics.
    Strength increases with more evidence and recency.
    Automatically fades when no new events are added.
    
    Statuses:
    - emerging: New theme, strength building (2.0 <= strength < 5.0)
    - active: Strong theme with recent activity (strength >= 5.0)
    - fading: Declining strength, no recent events
    - archived: Strength below threshold, no longer displayed
    """
    __tablename__ = "themes"
    
    # Primary key
    id: Mapped[str] = mapped_column(String(50), primary_key=True)
    
    # Core info
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    name_vi: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Aggregation
    related_event_ids: Mapped[Optional[List[str]]] = mapped_column(JSON, nullable=True)
    related_signal_ids: Mapped[Optional[List[str]]] = mapped_column(JSON, nullable=True)
    related_indicators: Mapped[Optional[List[str]]] = mapped_column(JSON, nullable=True)
    event_count: Mapped[int] = mapped_column(Integer, default=1)
    
    # Strength (auto-calculated by background job)
    strength: Mapped[float] = mapped_column(Float, default=1.0, index=True)
    peak_strength: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    # Timing
    first_seen: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    last_seen: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Status
    status: Mapped[str] = mapped_column(String(20), default='emerging', index=True)
    
    # Template link (if derived from causal template)
    template_id: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    
    # ==========================================================
    # TREND FIELDS (added by migration 005_trends_system)
    # These fields transform themes into "Trends" by adding:
    # - Unified narrative from all signal reasonings
    # - Urgency computed from signal expiry dates
    # - Signal statistics for tracking accuracy
    # ==========================================================
    
    # AI-synthesized narrative combining all signals' reasoning
    # Used in: TrendCard component to show summary of the trend
    # Generated by: LLM when signals are added to theme
    narrative: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Urgency level computed from earliest signal expiry
    # Used in: Trend sorting, Urgent section in UI, Sidebar badges
    # Values: 'urgent' (<7 days), 'watching' (7-14 days), 'low' (>14 days), None
    urgency: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    
    # Cached earliest signal expiry for efficient sorting
    # Updated when signals are added/removed/verified
    earliest_signal_expires: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Count of active signals linked to this trend
    # Used in: TrendCard to show "3 signals" badge
    signals_count: Mapped[int] = mapped_column(Integer, default=0)
    
    # Accuracy rate (0-1) for verified signals in this trend
    # Used in: TrendCard to show "2/3 correct" badge  
    signals_accuracy: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    # Count of verified signals (correct + wrong) for accuracy calculation
    signals_verified_count: Mapped[int] = mapped_column(Integer, default=0)
    
    # Count of correct signals
    signals_correct_count: Mapped[int] = mapped_column(Integer, default=0)
    
    # Relationships - use string reference to avoid circular import
    signals: Mapped[List["Signal"]] = relationship(
        "Signal",
        backref="theme",
        foreign_keys="Signal.theme_id"
    )
    
    # Indexes
    __table_args__ = (
        Index('idx_themes_status_strength', 'status', 'strength'),
    )
